#!/bin/bash

. /etc/os-release

RSTRNT_PKG_CMD=${RSTRNT_PKG_CMD:-yum}
if [ 0"$VERSION_ID" -gt 21 ]; then
    # Fedora 22 and newer use dnf as default
    RSTRNT_PKG_CMD=dnf
    if [ -f "/run/ostree-booted" ];then
        RSTRNT_PKG_ARGS=${RSTRNT_PKG_ARGS:--y --transient}
    fi
fi
