#!/bin/bash
#
# Synchronize tasks between SERVER/Client jobs
# on multihost machines.
#
# if firewall enable, the public setting also block sync
# [root@dell-per740-01 ~]# firewall-cmd --list-all
#public (active)
#  target: default
#  icmp-block-inversion: no
#  interfaces: eno1
#  sources:
#  services: cockpit dhcpv6-client ssh
#  ports:
#  protocols:
#  forward: yes
#  masquerade: no
#  forward-ports:
#  source-ports:
#  icmp-blocks:
#  rich rules:
systemctl is-active firewalld && systemctl stop firewalld
export TASKORDER=$(expr $TASKORDER + 1)
if [ -z "$SERVERS" ] || [ -z "$CLIENTS" ]; then
    echo "Skipping Multihost sync .. SERVERS/CLIENTS roles not set"
else
    echo "Multihost synchronization for Servers=$SERVERS Clients=$CLIENTS"
    rstrnt-sync-set -s DONE
    rstrnt-sync-block -s DONE --retry 30 $SERVERS $CLIENTS $DRIVER
fi
